# Generated by Django 3.2.4 on 2021-06-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateurs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('phone_number', models.CharField(max_length=20)),
                ('specialite', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('formateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formateurs.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, upload_to='')),
                ('rapport', models.FileField(blank=True, upload_to='')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.stagiaire')),
            ],
        ),
    ]
