# Generated by Django 3.2.4 on 2021-06-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0002_alter_document_stagiaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='stagiaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stagiaire.stagiaire'),
        ),
    ]
