# Generated by Django 3.2.4 on 2021-06-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0001_initial'),
        ('stagiaire', '0003_auto_20210618_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formateurs.formateur'),
        ),
    ]
