# Generated by Django 3.2.4 on 2021-06-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='title',
        ),
    ]
