# Generated by Django 3.2.4 on 2021-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attestation',
            field=models.FileField(blank=True, upload_to='attestation'),
        ),
    ]
