# Generated by Django 3.2.4 on 2021-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_remove_tache_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='axe',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
