# Generated by Django 3.2.4 on 2021-06-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_cahiercharge_cahiercharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axe',
            old_name='cahierCharge',
            new_name='axe',
        ),
    ]
