# Generated by Django 3.2.4 on 2021-06-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_rename_cahiercharge_axe_axe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axe',
            old_name='axe',
            new_name='cahierCharge',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='cahierCharge',
            new_name='axe',
        ),
    ]
