# Generated by Django 3.2.4 on 2021-06-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_auto_20210614_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('-created',)},
        ),
    ]
