# Generated by Django 3.2.4 on 2021-06-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0003_alter_stagiaire_specialite'),
        ('stages', '0006_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.stagiaire'),
        ),
    ]
